# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c65b2b1e5e8020cc3d384360623d7a37a1fca267dcb6aa61cf2d96633cb57d6e591b7cbe38bd1463c72bd94dbcc537f33f32d30015f846640e9f2765ccff246

test:
  secret_key_base: e46a794d9e5d74b92aff271667a222e69985328273925a28efcfbfa36679a01ff5434e6cbf72496fe8327396f0616c7c509ff29e85062671e5cf62c881fa286b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
